// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	WeddingAr1 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/wedding_ar/wedding_ar1.webp"
	WeddingAr2 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/wedding_ar/wedding_ar2.webp"
	WeddingAr3 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/wedding_ar/wedding_ar3.webp"
)
