// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	AnniversaryMsgBgEs   = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/chat/anniversary_msg_bg_es.jpg"
	AnniversaryMsgBgId   = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/chat/anniversary_msg_bg_id.jpg"
	AnniversaryMsgBgPt   = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/chat/anniversary_msg_bg_pt.jpg"
	AnniversaryMsgBgTh   = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/chat/anniversary_msg_bg_th.jpg"
	AnniversaryMsgBgZhCN = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/chat/anniversary_msg_bg_zh_CN.jpg"
	AnniversaryMsgBgZhTW = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/chat/anniversary_msg_bg_zh_TW.jpg"
	BgChatGiftCardDialog = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/chat/bg_chat_gift_card_dialog.webp"
	FortuneTellerBg      = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/chat/fortune_teller_bg.png"
	IntimacyActive       = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/chat/intimacy_active.webp"
)
