// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	AnniversaryMsgBgEs   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/chat/anniversary_msg_bg_es.jpg"
	AnniversaryMsgBgId   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/chat/anniversary_msg_bg_id.jpg"
	AnniversaryMsgBgPt   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/chat/anniversary_msg_bg_pt.jpg"
	AnniversaryMsgBgTh   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/chat/anniversary_msg_bg_th.jpg"
	AnniversaryMsgBgZhCN = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/chat/anniversary_msg_bg_zh_CN.jpg"
	AnniversaryMsgBgZhTW = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/chat/anniversary_msg_bg_zh_TW.jpg"
	BgChatGiftCardDialog = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/chat/bg_chat_gift_card_dialog.webp"
	IntimacyActive       = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/chat/intimacy_active.webp"
)
