// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	FamilyParty1 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/family_gathering_cn_id_es/FamilyParty1.png"
	FamilyParty3 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/family_gathering_cn_id_es/FamilyParty3.png"
	FamilyParty4 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/family_gathering_cn_id_es/FamilyParty4.png"
	FamilyParty5 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/family_gathering_cn_id_es/FamilyParty5.png"
	FamilyParty6 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/family_gathering_cn_id_es/FamilyParty6.png"
)
