// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	K1  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/female/1.png"
	K10 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/female/10.png"
	K11 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/female/11.png"
	K12 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/female/12.png"
	K13 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/female/13.png"
	K14 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/female/14.png"
	K15 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/female/15.png"
	K16 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/female/16.png"
	K17 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/female/17.png"
	K18 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/female/18.png"
	K19 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/female/19.png"
	K2  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/female/2.png"
	K20 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/female/20.png"
	K3  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/female/3.png"
	K4  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/female/4.png"
	K5  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/female/5.png"
	K6  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/female/6.png"
	K7  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/female/7.png"
	K8  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/female/8.png"
	K9  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/female/9.png"
)
