// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	Cat0    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/avatar/cat_0.webp"
	Cat1    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/avatar/cat_1.webp"
	Cat2    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/avatar/cat_2.webp"
	Cat3    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/avatar/cat_3.webp"
	Dog0    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/avatar/dog_0.webp"
	Dog1    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/avatar/dog_1.webp"
	Dog2    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/avatar/dog_2.webp"
	Dog3    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/avatar/dog_3.webp"
	Rabbit0 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/avatar/rabbit_0.webp"
	Rabbit1 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/avatar/rabbit_1.webp"
	Rabbit2 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/avatar/rabbit_2.webp"
	Rabbit3 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/avatar/rabbit_3.webp"
)
