// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	CharmRankHeaderBg     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/rank/charm_rank_header_bg.webp"
	CharmRankHeaderBgDark = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/rank/charm_rank_header_bg_dark.webp"
	MeetBg                = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/rank/meet_bg.png"
	Podium                = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/rank/podium.webp"
)
