// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	AbstractIcon = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb_cat/abstract_icon.png"
	AcuteIcon    = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb_cat/acute_icon.png"
	BigIcon      = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb_cat/big_icon.png"
	GameIcon     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb_cat/game_icon.png"
	HomeIcon     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb_cat/home_icon.png"
	Newicon      = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb_cat/newicon.png"
	OptionIcon   = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb_cat/option_icon.png"
	SmallIcon    = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb_cat/small_icon.png"
	TagIcon      = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb_cat/tag_icon.png"
	TypeIcon     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb_cat/type_icon.png"
)
