// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	BlindRingRankBg     = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/gift/blind_ring_rank_bg.webp"
	DiyGiftItemSelectBg = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/gift/diy_gift_item_select_bg.webp"
)
