// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	BlindRingRankBg     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/gift/blind_ring_rank_bg.webp"
	DiyGiftItemSelectBg = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/gift/diy_gift_item_select_bg.webp"
	FlowerGiftBox       = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/gift/flower_gift_box.png"
)
