// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	GoodLose                     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/were_wolf/good_lose.webp"
	GoodWin                      = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/were_wolf/good_win.webp"
	RoleBg                       = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/were_wolf/role_bg.png"
	WerewolfLose                 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/were_wolf/werewolf_lose.webp"
	WerewolfWin                  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/were_wolf/werewolf_win.webp"
	WolfGameTurnAwaitOtherAction = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/were_wolf/wolf_game_turn_await_other_action.webp"
	WolfGameTurnChangePlice      = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/were_wolf/wolf_game_turn_change_plice.webp"
	WolfGameTurnDateTimeBg       = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/were_wolf/wolf_game_turn_date_time_bg.webp"
	WolfGameTurnDateTimeDead     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/were_wolf/wolf_game_turn_date_time_dead.webp"
	WolfGameTurnDateTimePkBg     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/were_wolf/wolf_game_turn_date_time_pk_bg.webp"
	WolfGameTurnGameStartBg      = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/were_wolf/wolf_game_turn_game_start_bg.webp"
	WolfGameTurnJoinPlice        = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/were_wolf/wolf_game_turn_join_plice.webp"
	WolfGameTurnNightBg          = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/were_wolf/wolf_game_turn_night_bg.webp"
	WolfGameTurnNightDead        = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/were_wolf/wolf_game_turn_night_dead.webp"
	WolfGameTurnNightNoDead      = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/were_wolf/wolf_game_turn_night_no_dead.webp"
	WolfGameTurnNoChangePlice    = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/were_wolf/wolf_game_turn_no_change_plice.webp"
	WolfGameTurnUserBg           = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/were_wolf/wolf_game_turn_user_bg.webp"
	WolfGameTurnWaitBg           = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/were_wolf/wolf_game_turn_wait_bg.webp"
	WolfGameTurnWolfExplodeBg    = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/were_wolf/wolf_game_turn_wolf_explode_bg.webp"
	WolfGameTurnWolfSeerGood     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/were_wolf/wolf_game_turn_wolf_seer_good.webp"
	WolfGameTurnWolfSeerWolf     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/were_wolf/wolf_game_turn_wolf_seer_wolf.webp"
	WolfStateJoinPolicePk        = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/were_wolf/wolf_state_join_police_pk.webp"
)
