// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	CpFriendMic      = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_perks_icon/cp_friend_mic.png"
	RoomThemeImmerse = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_perks_icon/room_theme_immerse.png"
	VideoRoomSticker = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_perks_icon/video_room_sticker.png"
)
