// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	Gameparty1 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/game_party/gameparty1.webp"
	Gameparty2 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/game_party/gameparty2.webp"
	Gameparty3 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/game_party/gameparty3.webp"
	Gameparty4 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/game_party/gameparty4.webp"
	Gameparty5 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/game_party/gameparty5.webp"
	Gameparty6 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/game_party/gameparty6.webp"
)
