// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	PartyAr1 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/wild_party_ar/party_ar1.webp"
	PartyAr2 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/wild_party_ar/party_ar2.webp"
	PartyAr3 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/wild_party_ar/party_ar3.webp"
	PartyAr4 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/wild_party_ar/party_ar4.webp"
)
