// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	K1  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/th_robot_icon/1.JPG"
	K10 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/th_robot_icon/10.JPG"
	K11 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/th_robot_icon/11.JPG"
	K12 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/th_robot_icon/12.JPG"
	K13 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/th_robot_icon/13.JPG"
	K14 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/th_robot_icon/14.JPG"
	K15 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/th_robot_icon/15.JPG"
	K16 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/th_robot_icon/16.JPG"
	K17 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/th_robot_icon/17.JPG"
	K18 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/th_robot_icon/18.JPG"
	K19 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/th_robot_icon/19.JPG"
	K2  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/th_robot_icon/2.JPG"
	K20 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/th_robot_icon/20.JPG"
	K21 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/th_robot_icon/21.JPG"
	K3  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/th_robot_icon/3.JPG"
	K4  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/th_robot_icon/4.JPG"
	K5  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/th_robot_icon/5.JPG"
	K6  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/th_robot_icon/6.JPG"
	K8  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/th_robot_icon/8.JPG"
	K9  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/th_robot_icon/9.JPG"
)
