// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	ShareTopupSummitEn   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/topup_summit_event/share_topup_summit_en.png"
	ShareTopupSummitId   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/topup_summit_event/share_topup_summit_id.png"
	ShareTopupSummitPt   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/topup_summit_event/share_topup_summit_pt.png"
	ShareTopupSummitTh   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/topup_summit_event/share_topup_summit_th.png"
	ShareTopupSummitZhCn = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/topup_summit_event/share_topup_summit_zh_cn.png"
	ShareTopupSummitZhTw = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/topup_summit_event/share_topup_summit_zh_tw.png"
)
