// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	ActBoatCn = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/dragonboat/act_boat_cn.png"
	ActBoatEs = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/dragonboat/act_boat_es.png"
	ActBoatId = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/dragonboat/act_boat_id.png"
	ActBoatPt = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/dragonboat/act_boat_pt.png"
	ActBoatTh = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/dragonboat/act_boat_th.png"
	ActBoatTw = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/dragonboat/act_boat_tw.png"
)
