// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	BgNumLimitedCommodityEntry  = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/vip/bg_num_limited_commodity_entry.webp"
	BgTimeLimitedCommodityEntry = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/vip/bg_time_limited_commodity_entry.webp"
	CpRelationshipBgLoveHome    = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/vip/cp_relationship_bg_love_home.webp"
	CpRelationshipBgLoveLetter1 = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/vip/cp_relationship_bg_love_letter_1.webp"
	CpRelationshipBgSendInvite  = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/vip/cp_relationship_bg_send_invite.webp"
	CpRelationshipBgSuccessBack = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/vip/cp_relationship_bg_success_back.webp"
)
