// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	Game        = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/invite_reward_icon/game.png"
	HeadFrame   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/invite_reward_icon/head_frame.png"
	PostLike    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/invite_reward_icon/post_like.png"
	ProfileLike = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/invite_reward_icon/profile_like.png"
	Register    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/invite_reward_icon/register.png"
	RoomLike    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/invite_reward_icon/room_like.png"
	SignUp      = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/invite_reward_icon/sign_up.png"
	TopUp       = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/invite_reward_icon/top_up.png"
)
