// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	WeddingSchedule1 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/wedding/WeddingSchedule1.webp"
	WeddingSchedule2 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/wedding/WeddingSchedule2.webp"
	WeddingSchedule3 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/wedding/WeddingSchedule3.webp"
	WeddingSchedule4 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/wedding/WeddingSchedule4.webp"
	WeddingSchedule5 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/wedding/WeddingSchedule5.webp"
	WeddingSchedule6 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/wedding/WeddingSchedule6.webp"
)
