// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	Newbieparty1 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/newbie_party/newbieparty1.webp"
	Newbieparty2 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/newbie_party/newbieparty2.webp"
	Newbieparty3 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/newbie_party/newbieparty3.webp"
	Newbieparty4 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/newbie_party/newbieparty4.webp"
)
