// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	K1  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/2/vi/1.jpeg"
	K10 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/2/vi/10.jpeg"
	K11 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/2/vi/11.jpeg"
	K12 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/2/vi/12.jpeg"
	K13 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/2/vi/13.jpeg"
	K14 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/2/vi/14.jpeg"
	K15 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/2/vi/15.jpeg"
	K16 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/2/vi/16.jpeg"
	K17 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/2/vi/17.jpeg"
	K18 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/2/vi/18.jpeg"
	K19 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/2/vi/19.jpeg"
	K2  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/2/vi/2.jpeg"
	K20 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/2/vi/20.jpeg"
	K21 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/2/vi/21.jpeg"
	K3  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/2/vi/3.jpeg"
	K4  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/2/vi/4.jpeg"
	K5  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/2/vi/5.jpeg"
	K6  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/2/vi/6.jpeg"
	K7  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/2/vi/7.jpeg"
	K8  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/2/vi/8.jpeg"
	K9  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/2/vi/9.jpeg"
)
