// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	Singing1 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/singing/Singing1.webp"
	Singing2 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/singing/Singing2.webp"
	Singing4 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/singing/Singing4.webp"
	Singing5 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/singing/Singing5.webp"
	Singing6 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/singing/Singing6.webp"
	Singing8 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/singing/Singing8.webp"
)
