// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	BombAlmost       = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb/Bomb-almost.webp"
	BombNormal       = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb/Bomb-normal.webp"
	BombExploded     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb/bomb-exploded.webp"
	BombExploded2311 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb/bomb-exploded_23-11.webp"
	Chicken          = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb/chicken.webp"
	Exploded         = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb/exploded.mp3"
	Fishman          = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb/fishman.webp"
	Frog             = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb/frog.webp"
	Mosaic           = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb/mosaic.webp"
	Mule             = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb/mule.webp"
	Shrek            = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb/shrek.webp"
	Tick3SecFast     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb/tick_3_sec_fast.mp3"
	Tick3SecSlow     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb/tick_3_sec_slow.mp3"
	UserExploded     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb/user-exploded.webp"
	Wam              = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/bomb/wam.webp"
)
