// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	MatchAr1 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/matchmaking_ar/match_ar1.png"
	MatchAr2 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/matchmaking_ar/match_ar2.png"
)
