// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	PartyAr1 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/wild_party_ar/party_ar1.png"
	PartyAr2 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/wild_party_ar/party_ar2.png"
	PartyAr3 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/wild_party_ar/party_ar3.png"
	PartyAr4 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/wild_party_ar/party_ar4.png"
)
