// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	FateGiftScenesAnim = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/mp4/fate_gift_scenes_anim.mp4"
)
