// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	HeaderEsCoin = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/user_ops/first_recharge_gift/regular_2022081103/header/header_es_coin.webp"
)
