// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	Newbieparty1 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/newbie_party/newbieparty1.png"
	Newbieparty2 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/newbie_party/newbieparty2.png"
	Newbieparty3 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/newbie_party/newbieparty3.png"
	Newbieparty4 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/newbie_party/newbieparty4.png"
)
