// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	Wildparty1 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/wild_party/wildparty1.png"
	Wildparty2 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/wild_party/wildparty2.png"
	Wildparty3 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/wild_party/wildparty3.png"
	Wildparty4 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/wild_party/wildparty4.png"
	Wildparty5 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/wild_party/wildparty5.png"
)
