// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	EggHuntDesignation55 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_designation_55.png"
	EggHuntDesignation70 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_designation_70.png"
	EggHuntShareAr       = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_ar.png"
	EggHuntShareAr1      = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_ar_1.png"
	EggHuntShareEn       = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_en.png"
	EggHuntShareEn1      = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_en_1.webp"
	EggHuntShareEs       = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_es.png"
	EggHuntShareEs1      = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_es_1.webp"
	EggHuntShareId       = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_id.png"
	EggHuntShareId1      = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_id_1.webp"
	EggHuntSharePt       = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_pt.png"
	EggHuntSharePt1      = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_pt_1.webp"
	EggHuntShareTh       = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_th.png"
	EggHuntShareTh1      = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_th_1.webp"
	EggHuntShareVi       = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_vi.png"
	EggHuntShareVi1      = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_vi_1.png"
	EggHuntShareZhCn     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_zh_cn.png"
	EggHuntShareZhCn1    = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_zh_cn_1.webp"
	EggHuntShareZhTw     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_zh_tw.png"
	EggHuntShareZhTw1    = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_zh_tw_1.webp"
)
