// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	EggHuntShareAr   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_ar.png"
	EggHuntShareEn   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_en.png"
	EggHuntShareEs   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_es.png"
	EggHuntShareId   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_id.png"
	EggHuntSharePt   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_pt.png"
	EggHuntShareTh   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_th.png"
	EggHuntShareVi   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_vi.png"
	EggHuntShareZhCn = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_zh_cn.png"
	EggHuntShareZhTw = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_zh_tw.png"
)
