// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	EggHuntShareAr    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_ar.png"
	EggHuntShareEn    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_en.png"
	EggHuntShareEn1   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_en_1.webp"
	EggHuntShareEs    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_es.png"
	EggHuntShareEs1   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_es_1.webp"
	EggHuntShareId    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_id.png"
	EggHuntShareId1   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_id_1.webp"
	EggHuntSharePt    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_pt.png"
	EggHuntSharePt1   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_pt_1.webp"
	EggHuntShareTh    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_th.png"
	EggHuntShareTh1   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_th_1.webp"
	EggHuntShareVi    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_vi.png"
	EggHuntShareZhCn  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_zh_cn.png"
	EggHuntShareZhCn1 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_zh_cn_1.webp"
	EggHuntShareZhTw  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_zh_tw.png"
	EggHuntShareZhTw1 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/egg_hunt_event/egg_hunt_share_zh_tw_1.webp"
)
