// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	WeddingScheduleVN1 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/wedding_vi/WeddingScheduleVN1.webp"
	WeddingScheduleVN2 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/wedding_vi/WeddingScheduleVN2.webp"
	WeddingScheduleVN4 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/wedding_vi/WeddingScheduleVN4.webp"
	WeddingScheduleVN5 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/wedding_vi/WeddingScheduleVN5.webp"
	WeddingScheduleVN6 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/wedding_vi/WeddingScheduleVN6.webp"
)
