// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	RamadanImImage = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/lucky_card_event/ramadan_im_image.png"
)
