// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	Flower1       = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/interact_mark/flower_1.png"
	Flower2       = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/interact_mark/flower_2.png"
	GroupBgFlower = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/interact_mark/group_bg_flower.png"
	GroupBgLeaves = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/interact_mark/group_bg_leaves.png"
	GroupBgSeed   = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/interact_mark/group_bg_seed.png"
	Leaves1       = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/interact_mark/leaves_1.png"
	Leaves2       = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/interact_mark/leaves_2.png"
	Leaves3       = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/interact_mark/leaves_3.png"
	Leaves4       = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/interact_mark/leaves_4.png"
	Leaves5       = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/interact_mark/leaves_5.png"
	Leaves6       = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/interact_mark/leaves_6.png"
	Seed1         = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/interact_mark/seed_1.png"
	Seed2         = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/interact_mark/seed_2.png"
	Seed3         = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/interact_mark/seed_3.png"
)
