// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	K1  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/male/1.png"
	K10 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/male/10.png"
	K11 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/male/11.png"
	K12 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/male/12.png"
	K13 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/male/13.png"
	K14 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/male/14.png"
	K15 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/male/15.png"
	K16 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/male/16.png"
	K17 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/male/17.png"
	K2  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/male/2.png"
	K3  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/male/3.png"
	K4  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/male/4.png"
	K5  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/male/5.png"
	K6  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/male/6.png"
	K7  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/male/7.png"
	K8  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/male/8.png"
	K9  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/cn/male/9.png"
)
