// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	AbstractIcon = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/cocos-monopoly/abstract_icon.png"
	AcuteIcon    = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/cocos-monopoly/acute_icon.png"
	BigIcon      = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/cocos-monopoly/big_icon.png"
	GameIcon     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/cocos-monopoly/game_icon.png"
	HomeIcon     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/cocos-monopoly/home_icon.png"
	Newicon      = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/cocos-monopoly/newicon.png"
	OptionIcon   = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/cocos-monopoly/option_icon.png"
	SmallIcon    = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/cocos-monopoly/small_icon.png"
	TagIcon      = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/cocos-monopoly/tag_icon.png"
	TypeIcon     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/cocos-monopoly/type_icon.png"
)
