// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	Anonymousletter1 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/anonymous_letter_pt/anonymousletter1.png"
	Anonymousletter2 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/anonymous_letter_pt/anonymousletter2.png"
	Anonymousletter3 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/anonymous_letter_pt/anonymousletter3.png"
	Anonymousletter4 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/anonymous_letter_pt/anonymousletter4.png"
)
