// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	Accompany  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/new_room_icon/accompany.png"
	Chat       = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/new_room_icon/chat.png"
	Game       = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/new_room_icon/game.png"
	Ktv        = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/new_room_icon/ktv.png"
	Listensong = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/new_room_icon/listensong.png"
	Video      = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/new_room_icon/video.png"
)
