// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	HeaderAr     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/migrated/newcomer_2022081102/header/header_ar.png"
	HeaderEn     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/migrated/newcomer_2022081102/header/header_en.png"
	HeaderEs     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/migrated/newcomer_2022081102/header/header_es.png"
	HeaderEsCoin = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/migrated/newcomer_2022081102/header/header_es_coin.png"
	HeaderId     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/migrated/newcomer_2022081102/header/header_id.png"
	HeaderPt     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/migrated/newcomer_2022081102/header/header_pt.png"
	HeaderPtCoin = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/migrated/newcomer_2022081102/header/header_pt_coin.png"
	HeaderTh     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/migrated/newcomer_2022081102/header/header_th.png"
	HeaderVi     = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/migrated/newcomer_2022081102/header/header_vi.png"
	HeaderZhCn   = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/migrated/newcomer_2022081102/header/header_zh_cn.png"
	HeaderZhTw   = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/migrated/newcomer_2022081102/header/header_zh_tw.png"
)
