// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	IconAccompany   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/match/icon_accompany.webp"
	IconAccompany2  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/match/icon_accompany2.webp"
	IconBilliards   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/match/icon_billiards.webp"
	IconBilliards2  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/match/icon_billiards2.webp"
	IconCarrom      = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/match/icon_carrom.webp"
	IconCarrom2     = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/match/icon_carrom2.webp"
	IconChat        = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/match/icon_chat.webp"
	IconChat2       = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/match/icon_chat2.webp"
	IconKtv         = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/match/icon_ktv.webp"
	IconKtv2        = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/match/icon_ktv2.webp"
	IconLandlord    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/match/icon_landlord.webp"
	IconLandlord2   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/match/icon_landlord2.webp"
	IconListensong  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/match/icon_listensong.webp"
	IconListensong2 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/match/icon_listensong2.webp"
	IconLudo        = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/match/icon_ludo.webp"
	IconLudo2       = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/match/icon_ludo2.webp"
	IconMajiang     = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/match/icon_majiang.webp"
	IconMajiang2    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/match/icon_majiang2.webp"
	IconTetris      = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/match/icon_tetris.webp"
	IconTetris2     = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/match/icon_tetris2.webp"
	IconUno         = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/match/icon_uno.webp"
	IconUno2        = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/match/icon_uno2.webp"
	IconVideo       = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/match/icon_video.webp"
	IconVideo2      = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/match/icon_video2.webp"
)
