// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	Fireworks  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_hot_award/fireworks.mp4"
	GoldPetal  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_hot_award/gold_petal.mp4"
	GoldRibbon = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_hot_award/gold_ribbon.mp4"
	Petal      = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_hot_award/petal.mp4"
	Ribbon     = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_hot_award/ribbon.mp4"
)
