// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	GuessVeeka        = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/new_room_icon_v2/guess_veeka.png"
	LayaGameBigtwo    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/new_room_icon_v2/laya_game_bigtwo.png"
	LayaGameBilliards = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/new_room_icon_v2/laya_game_billiards.png"
	LayaGameCarrom    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/new_room_icon_v2/laya_game_carrom.png"
	LayaGameDomino    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/new_room_icon_v2/laya_game_domino.png"
	LayaGameDummy     = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/new_room_icon_v2/laya_game_dummy.png"
	LayaGameFootball  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/new_room_icon_v2/laya_game_football.png"
	LayaGameLandlord  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/new_room_icon_v2/laya_game_landlord.png"
	LayaGameLudo      = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/new_room_icon_v2/laya_game_ludo.png"
	LayaGameTetris    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/new_room_icon_v2/laya_game_tetris.png"
	LayaGameTruco     = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/new_room_icon_v2/laya_game_truco.png"
	LayaGameUno       = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/new_room_icon_v2/laya_game_uno.png"
	MajorityVeeka     = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/new_room_icon_v2/majority_veeka.png"
	UnderVeeka        = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/new_room_icon_v2/under_veeka.png"
	WolfVeeka         = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/new_room_icon_v2/wolf_veeka.png"
)
