// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	BgFriendInRoom    = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/bbcore/bg_friend_in_room.webp"
	IcNoPublishMoment = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/bbcore/ic_no_publish_moment.webp"
)
