// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	K1  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/male/1.jpg"
	K10 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/male/10.jpg"
	K11 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/male/11.jpg"
	K12 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/male/12.jpg"
	K13 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/male/13.jpg"
	K14 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/male/14.jpg"
	K15 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/male/15.jpg"
	K2  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/male/2.jpg"
	K3  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/male/3.jpg"
	K4  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/male/4.jpg"
	K5  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/male/5.jpg"
	K6  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/male/6.jpg"
	K7  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/male/7.jpg"
	K8  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/male/8.jpg"
	K9  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/male/9.jpg"
)
