// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	K1  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/female/1.jpg"
	K10 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/female/10.jpg"
	K11 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/female/11.jpg"
	K12 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/female/12.jpg"
	K13 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/female/13.jpg"
	K14 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/female/14.jpg"
	K15 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/female/15.jpg"
	K2  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/female/2.jpg"
	K3  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/female/3.jpg"
	K4  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/female/4.jpg"
	K5  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/female/5.jpg"
	K6  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/female/6.jpg"
	K7  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/female/7.jpg"
	K8  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/female/8.jpg"
	K9  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/id/female/9.jpg"
)
