// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	WeddingSchedule1 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/wedding/WeddingSchedule1.png"
	WeddingSchedule2 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/wedding/WeddingSchedule2.png"
	WeddingSchedule3 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/wedding/WeddingSchedule3.png"
	WeddingSchedule4 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/wedding/WeddingSchedule4.png"
	WeddingSchedule5 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/wedding/WeddingSchedule5.png"
	WeddingSchedule6 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/wedding/WeddingSchedule6.png"
)
