// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	HeaderEsCoin = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/user_ops/first_recharge_gift/newcomer_2022081102/header/header_es_coin.png"
)
