// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	Singing2 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/singing_th_vi/Singing2.png"
	Singing4 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/singing_th_vi/Singing4.png"
	Singing5 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/singing_th_vi/Singing5.png"
	Singing6 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/singing_th_vi/Singing6.png"
	Singing8 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/singing_th_vi/Singing8.png"
)
