// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	Bag                = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/profile/bag.png"
	FireBg             = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/profile/fire_bg.webp"
	Nobility           = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/profile/nobility.png"
	PopularBackground0 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/profile/popular_background_0.webp"
	PopularBackground1 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/profile/popular_background_1.webp"
	PopularBackground2 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/profile/popular_background_2.webp"
	PopularBackground3 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/profile/popular_background_3.webp"
	PopularBackground4 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/profile/popular_background_4.webp"
	PopularBackground5 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/profile/popular_background_5.webp"
	PopularBackground6 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/profile/popular_background_6.webp"
	PopularBackground7 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/profile/popular_background_7.webp"
	PopularBackground8 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/profile/popular_background_8.webp"
	PopularBackground9 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/profile/popular_background_9.webp"
	Shop               = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/profile/shop.png"
	Vip                = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/profile/vip.png"
)
