// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	FamilyCelebrityLabelAr   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_celebrity_label_ar.png"
	FamilyCelebrityLabelEn   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_celebrity_label_en.png"
	FamilyCelebrityLabelEs   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_celebrity_label_es.png"
	FamilyCelebrityLabelId   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_celebrity_label_id.png"
	FamilyCelebrityLabelPt   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_celebrity_label_pt.png"
	FamilyCelebrityLabelTh   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_celebrity_label_th.png"
	FamilyCelebrityLabelVi   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_celebrity_label_vi.png"
	FamilyCelebrityLabelZhCn = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_celebrity_label_zh_cn.png"
	FamilyCelebrityLabelZhTw = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_celebrity_label_zh_tw.png"
	FamilyLevel1             = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_level_1.png"
	FamilyLevel1Small        = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_level_1_small.png"
	FamilyLevel2             = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_level_2.png"
	FamilyLevel2Small        = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_level_2_small.png"
	FamilyLevel3             = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_level_3.png"
	FamilyLevel3Small        = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_level_3_small.png"
	FamilyLevel4             = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_level_4.png"
	FamilyLevel4Small        = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_level_4_small.png"
	FamilyLevel5             = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_level_5.png"
	FamilyLevel5Small        = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_level_5_small.png"
	FamilyLevel6             = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_level_6.png"
	FamilyLevel6Small        = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_level_6_small.png"
	FamilyLevel7             = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_level_7.png"
	FamilyLevel7Small        = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_level_7_small.png"
)
