// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	FamilyCelebrityTagAr   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_celebrity_tag_ar.png"
	FamilyCelebrityTagEn   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_celebrity_tag_en.png"
	FamilyCelebrityTagEs   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_celebrity_tag_es.png"
	FamilyCelebrityTagId   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_celebrity_tag_id.png"
	FamilyCelebrityTagPt   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_celebrity_tag_pt.png"
	FamilyCelebrityTagTh   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_celebrity_tag_th.png"
	FamilyCelebrityTagVi   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_celebrity_tag_vi.png"
	FamilyCelebrityTagZhCn = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_celebrity_tag_zh_cn.png"
	FamilyCelebrityTagZhTw = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/family/family_celebrity_tag_zh_tw.png"
)
