// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	SoundPairFail    = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/bbroom/blind_date/sound_pair_fail.mp3"
	SoundPairSuccess = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/bbroom/blind_date/sound_pair_success.mp3"
)
