// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	CpRing       = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/cp_valentine_event/cp_ring.png"
	TianZuoZhiHe = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/cp_valentine_event/tian_zuo_zhi_he.png"
)
