// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	Background     = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/old/background.png"
	GoldBean       = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/old/gold_bean.png"
	Header         = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/old/header.png"
	HeaderWithCoin = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/old/header_with_coin.png"
	Texture        = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/old/texture.png"
)
