// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	BannerEn   = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/migrated/newcomer_2022081101/banner/banner_en.webp"
	BannerEs   = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/migrated/newcomer_2022081101/banner/banner_es.webp"
	BannerId   = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/migrated/newcomer_2022081101/banner/banner_id.webp"
	BannerPt   = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/migrated/newcomer_2022081101/banner/banner_pt.webp"
	BannerTh   = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/migrated/newcomer_2022081101/banner/banner_th.webp"
	BannerZhCn = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/migrated/newcomer_2022081101/banner/banner_zh_cn.webp"
	BannerZhTw = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/migrated/newcomer_2022081101/banner/banner_zh_tw.webp"
)
