// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	GamepartyAr1 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/game_party_ar/gameparty_ar1.png"
	GamepartyAr2 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/game_party_ar/gameparty_ar2.png"
	GamepartyAr3 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates_new/game_party_ar/gameparty_ar3.png"
)
