// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	AbstractIcon = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/2048/abstract_icon.png"
	AcuteIcon    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/2048/acute_icon.png"
	BigIcon      = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/2048/big_icon.png"
	GameIcon     = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/2048/game_icon.png"
	HomeIcon     = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/2048/home_icon.png"
	Newicon      = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/2048/newicon.png"
	OptionIcon   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/2048/option_icon.png"
	SmallIcon    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/2048/small_icon.png"
	TagIcon      = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/2048/tag_icon.png"
	TypeIcon     = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/2048/type_icon.png"
)
