// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	AbstractIcon = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/cocos-butt/abstract_icon.png"
	AcuteIcon    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/cocos-butt/acute_icon.png"
	BigIcon      = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/cocos-butt/big_icon.png"
	GameIcon     = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/cocos-butt/game_icon.png"
	HomeIcon     = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/cocos-butt/home_icon.png"
	Newicon      = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/cocos-butt/newicon.png"
	OptionIcon   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/cocos-butt/option_icon.png"
	SmallIcon    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/cocos-butt/small_icon.png"
	TagIcon      = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/cocos-butt/tag_icon.png"
	TypeIcon     = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game/cocos-butt/type_icon.png"
)
