// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	NewVeekaCoin  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/mission1/new_veeka_coin.png"
	VeekaGoldBean = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/mission1/veeka_gold_bean.png"
	VeekaPtCoin   = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/mission1/veeka_pt_coin.png"
)
