// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	K1  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/female/1.jpeg"
	K10 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/female/10.jpeg"
	K11 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/female/11.jpeg"
	K12 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/female/12.jpeg"
	K13 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/female/13.jpeg"
	K14 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/female/14.jpeg"
	K15 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/female/15.jpeg"
	K2  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/female/2.jpeg"
	K3  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/female/3.jpeg"
	K4  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/female/4.jpeg"
	K5  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/female/5.jpeg"
	K6  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/female/6.jpeg"
	K7  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/female/7.png"
	K8  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/female/8.png"
	K9  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/female/9.jpeg"
)
