// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	Bg0  = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/cp/bg_0.webp"
	Bg1  = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/cp/bg_1.webp"
	Bg10 = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/cp/bg_10.webp"
	Bg2  = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/cp/bg_2.webp"
	Bg3  = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/cp/bg_3.webp"
	Bg4  = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/cp/bg_4.webp"
	Bg5  = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/cp/bg_5.webp"
	Bg6  = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/cp/bg_6.webp"
	Bg7  = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/cp/bg_7.webp"
	Bg8  = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/cp/bg_8.webp"
	Bg9  = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/cp/bg_9.webp"
)
