// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	Header = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/migrated/newcomer_2023010601/header/header.webp"
)
