// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	K1  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/1/vi/1.jpeg"
	K10 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/1/vi/10.jpeg"
	K11 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/1/vi/11.jpeg"
	K12 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/1/vi/12.jpeg"
	K13 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/1/vi/13.jpeg"
	K14 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/1/vi/14.jpeg"
	K15 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/1/vi/15.jpeg"
	K16 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/1/vi/16.jpeg"
	K17 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/1/vi/17.jpeg"
	K18 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/1/vi/18.jpeg"
	K19 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/1/vi/19.jpeg"
	K2  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/1/vi/2.jpeg"
	K20 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/1/vi/20.jpeg"
	K3  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/1/vi/3.jpeg"
	K4  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/1/vi/4.jpeg"
	K5  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/1/vi/5.jpeg"
	K6  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/1/vi/6.jpeg"
	K7  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/1/vi/7.jpeg"
	K8  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/1/vi/8.jpeg"
	K9  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/userlogin/1/vi/9.jpeg"
)
