// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	GuessQueueModeGuess        = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_queue_mode_guess.webp"
	GuessQueueModeQueue        = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_queue_mode_queue.webp"
	GuessStartBgForVisitorAr   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_for_visitor_ar.webp"
	GuessStartBgForVisitorEn   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_for_visitor_en.webp"
	GuessStartBgForVisitorId   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_for_visitor_id.webp"
	GuessStartBgForVisitorKo   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_for_visitor_ko.webp"
	GuessStartBgForVisitorMs   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_for_visitor_ms.webp"
	GuessStartBgForVisitorTh   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_for_visitor_th.webp"
	GuessStartBgForVisitorTr   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_for_visitor_tr.webp"
	GuessStartBgForVisitorVi   = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_for_visitor_vi.webp"
	GuessStartBgForVisitorZhCN = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_for_visitor_zh_CN.webp"
	GuessStartBgForVisitorZhTW = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_for_visitor_zh_TW.webp"
)
