// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	GuessQueueModeGuess        = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_queue_mode_guess.webp"
	GuessQueueModeQueue        = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_queue_mode_queue.webp"
	GuessStartBgAr             = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_ar.webp"
	GuessStartBgEn             = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_en.webp"
	GuessStartBgForVisitorAr   = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_for_visitor_ar.webp"
	GuessStartBgForVisitorEn   = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_for_visitor_en.webp"
	GuessStartBgForVisitorId   = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_for_visitor_id.webp"
	GuessStartBgForVisitorKo   = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_for_visitor_ko.webp"
	GuessStartBgForVisitorMs   = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_for_visitor_ms.webp"
	GuessStartBgForVisitorTh   = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_for_visitor_th.webp"
	GuessStartBgForVisitorTr   = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_for_visitor_tr.webp"
	GuessStartBgForVisitorVi   = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_for_visitor_vi.webp"
	GuessStartBgForVisitorZhCN = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_for_visitor_zh_CN.webp"
	GuessStartBgForVisitorZhTW = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_for_visitor_zh_TW.webp"
	GuessStartBgId             = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_id.webp"
	GuessStartBgKo             = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_ko.webp"
	GuessStartBgMs             = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_ms.webp"
	GuessStartBgTh             = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_th.webp"
	GuessStartBgTr             = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_tr.webp"
	GuessStartBgVi             = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_vi.webp"
	GuessStartBgZhCN           = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_zh_CN.webp"
	GuessStartBgZhTW           = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/draw_guess/guess_start_bg_zh_TW.webp"
)
