// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	Birthdayparty1 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/birthday_party_th_vi/birthdayparty1.webp"
	Birthdayparty3 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/birthday_party_th_vi/birthdayparty3.webp"
	Birthdayparty4 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/birthday_party_th_vi/birthdayparty4.webp"
	Birthdayparty5 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/room_notice_templates/birthday_party_th_vi/birthdayparty5.webp"
)
