// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	K1  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/male/1.jpeg"
	K10 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/male/10.jpeg"
	K11 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/male/11.jpeg"
	K12 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/male/12.jpeg"
	K13 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/male/13.jpeg"
	K14 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/male/14.jpeg"
	K15 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/male/15.jpeg"
	K16 = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/male/16.jpeg"
	K2  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/male/2.jpeg"
	K3  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/male/3.jpeg"
	K4  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/male/4.jpeg"
	K5  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/male/5.jpeg"
	K6  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/male/6.jpeg"
	K7  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/male/7.jpeg"
	K8  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/male/8.jpeg"
	K9  = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/pt/male/9.jpeg"
)
