// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	TemplateB = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/notification/template_b.png"
	TemplateC = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/notification/template_c.png"
)
