// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	Cat0          = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/full/cat_0.webp"
	Cat1          = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/full/cat_1.webp"
	Cat1Locked    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/full/cat_1_locked.webp"
	Cat2          = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/full/cat_2.webp"
	Cat2Locked    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/full/cat_2_locked.webp"
	Cat3          = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/full/cat_3.webp"
	Cat3Locked    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/full/cat_3_locked.webp"
	Dog0          = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/full/dog_0.webp"
	Dog1          = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/full/dog_1.webp"
	Dog1Locked    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/full/dog_1_locked.webp"
	Dog2          = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/full/dog_2.webp"
	Dog2Locked    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/full/dog_2_locked.webp"
	Dog3          = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/full/dog_3.webp"
	Dog3Locked    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/full/dog_3_locked.webp"
	Rabbit0       = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/full/rabbit_0.webp"
	Rabbit1       = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/full/rabbit_1.webp"
	Rabbit1Locked = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/full/rabbit_1_locked.webp"
	Rabbit2       = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/full/rabbit_2.webp"
	Rabbit2Locked = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/full/rabbit_2_locked.webp"
	Rabbit3       = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/full/rabbit_3.webp"
	Rabbit3Locked = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/full/rabbit_3_locked.webp"
)
