// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	K202StringV1Es = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/appres/202_string_v1_es.json"
	K202StringV1Pt = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/appres/202_string_v1_pt.json"
)
