// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	BackgroundAutumn        = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/background_autumn.webp"
	BackgroundBeach         = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/background_beach.webp"
	BackgroundCastle        = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/background_castle.webp"
	BackgroundCityStreet    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/background_city_street.webp"
	BackgroundColourfulRoom = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/background_colourful_room.webp"
	BackgroundCountrySide   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/background_country_side.webp"
	BackgroundDefault       = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/background_default.webp"
	BackgroundFutureCity    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/background_future_city.webp"
	BackgroundGrassField    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/background_grass_field.webp"
	BackgroundPinkRoom      = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/background_pink_room.webp"
	BackgroundSchool        = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/background_school.webp"
	BackgroundStarryNight   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/background_starry_night.webp"
	ThumbnailAutumn         = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/thumbnail_autumn.webp"
	ThumbnailBeach          = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/thumbnail_beach.webp"
	ThumbnailCastle         = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/thumbnail_castle.webp"
	ThumbnailCityStreet     = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/thumbnail_city_street.webp"
	ThumbnailColourfulRoom  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/thumbnail_colourful_room.webp"
	ThumbnailCountrySide    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/thumbnail_country_side.webp"
	ThumbnailDefault        = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/thumbnail_default.webp"
	ThumbnailFutureCity     = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/thumbnail_future_city.webp"
	ThumbnailGrassField     = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/thumbnail_grass_field.webp"
	ThumbnailPinkRoom       = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/thumbnail_pink_room.webp"
	ThumbnailSchool         = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/thumbnail_school.webp"
	ThumbnailStarryNight    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/thumbnail_starry_night.webp"
)
