// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	BackgroundAutumn        = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/background_autumn.png"
	BackgroundBeach         = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/background_beach.png"
	BackgroundCastle        = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/background_castle.png"
	BackgroundCityStreet    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/background_city_street.png"
	BackgroundColourfulRoom = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/background_colourful_room.png"
	BackgroundCountrySide   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/background_country_side.png"
	BackgroundDefault       = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/background_default.png"
	BackgroundFutureCity    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/background_future_city.png"
	BackgroundGrassField    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/background_grass_field.png"
	BackgroundPinkRoom      = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/background_pink_room.png"
	BackgroundSchool        = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/background_school.png"
	BackgroundStarryNight   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/background_starry_night.png"
	ThumbnailAutumn         = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/thumbnail_autumn.png"
	ThumbnailBeach          = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/thumbnail_beach.png"
	ThumbnailCastle         = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/thumbnail_castle.png"
	ThumbnailCityStreet     = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/thumbnail_city_street.png"
	ThumbnailColourfulRoom  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/thumbnail_colourful_room.png"
	ThumbnailCountrySide    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/thumbnail_country_side.png"
	ThumbnailDefault        = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/thumbnail_default.png"
	ThumbnailFutureCity     = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/thumbnail_future_city.png"
	ThumbnailGrassField     = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/thumbnail_grass_field.png"
	ThumbnailPinkRoom       = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/thumbnail_pink_room.png"
	ThumbnailSchool         = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/thumbnail_school.png"
	ThumbnailStarryNight    = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/pets/home/bg/thumbnail_starry_night.png"
)
