// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	RacingWinForegroundImg = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/horse_racing/racing_win_foreground_img.webp"
)
