// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	K1  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/th/male/1.jpeg"
	K10 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/th/male/10.JPG"
	K11 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/th/male/11.JPG"
	K12 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/th/male/12.JPG"
	K13 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/th/male/13.JPG"
	K14 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/th/male/14.JPG"
	K15 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/th/male/15.JPG"
	K16 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/th/male/16.JPG"
	K17 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/th/male/17.JPG"
	K18 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/th/male/18.JPG"
	K2  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/th/male/2.jpeg"
	K3  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/th/male/3.jpeg"
	K4  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/th/male/4.jpeg"
	K5  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/th/male/5.JPG"
	K6  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/th/male/6.JPG"
	K7  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/th/male/7.JPG"
	K8  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/th/male/8.JPG"
	K9  = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/game_robot_icon/th/male/9.JPG"
)
