// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	GiftIconBG = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/old/newcomer_2022081101/gift_icon_BG.webp"
)
