// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	Chatbg = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/greet_gift/chatbg.png"
	Rose   = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/greet_gift/rose.png"
)
