// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	Dark0001 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/user/avatar/male/dark_0001.png"
	Dark0002 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/user/avatar/male/dark_0002.png"
	Dark0003 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/user/avatar/male/dark_0003.png"
	Dark0004 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/user/avatar/male/dark_0004.png"
	Fair0001 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/user/avatar/male/fair_0001.png"
	Fair0002 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/user/avatar/male/fair_0002.png"
	Fair0003 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/user/avatar/male/fair_0003.png"
	Fair0004 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/user/avatar/male/fair_0004.png"
	Fair0005 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/user/avatar/male/fair_0005.png"
	Fair0006 = "https://partying.oss-ap-southeast-1.aliyuncs.com/static/veeka/user/avatar/male/fair_0006.png"
)
