// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	Type3Banner     = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/type3_banner.webp"
	Type3GiftIconBG = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/type3_gift_icon_BG.webp"
	Type3Header     = "https://partying.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/type3_header.webp"
)
