// Code generated by gen-static-assets; DO NOT EDIT.
package oss

const (
	LotteryBanner      = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/lottery_banner.webp"
	Type1Banner        = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/type1_banner.webp"
	Type1Header        = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/type1_header.webp"
	Type1OldGiftIconBG = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/type1_old_gift_icon_BG.webp"
	Type2OldGiftIconBG = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/type2_old_gift_icon_BG.webp"
	Type3Banner        = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/type3_banner.webp"
	Type3BannerCoin    = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/type3_banner_coin.webp"
	Type3GiftIconBG    = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/type3_gift_icon_BG.webp"
	Type3Header        = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/type3_header.webp"
	Type3HeaderCoin    = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/type3_header_coin.webp"
	Type3OldGiftIconBG = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/type3_old_gift_icon_BG.webp"
	Type4Banner        = "https://veeka-app-public.oss-ap-southeast-1.aliyuncs.com/veeka/assets/recharge_popup/type4_banner.webp"
)
